# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [2]:
import numpy as np

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [2]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

['2' 'bottom' 'top' '4.5' 'top' '4.5' '2' 'top' 'top' 'top']


Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [3]:
# Місце для Вашого коду
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
print(np.random.choice(a, size=(1), replace=False))


[3]


Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [5]:
# Місце для Вашого коду
print(np.random.choice(a, size=(4, 6), replace=True))


[[7 0 2 7 4 9]
 [7 1 7 7 3 6]
 [2 5 4 0 2 0]
 [1 2 2 1 3 5]]


### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [5]:
low = 0
high = 5
size = 10
print(np.random.randint(low=low, high=high, size=size))

[3 1 4 2 1 4 1 1 0 4]


Згенеруйте одну випадкову цифру.

In [21]:
# Місце для Вашого коду
print(np.random.randint(10))


0


Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [24]:
# Місце для Вашого коду
print(np.random.randint(10, 100, size=(4, 5)))


[[21 22 33 41 20]
 [42 33 29 80 10]
 [88 12 31 99 25]
 [19 38 14 39 38]]


### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [8]:
size = None
print(np.random.sample(size=size))

0.3369603119037976


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [27]:
# Місце для Вашого коду

np.random.sample(size=(3, 4))

array([[0.76478774, 0.82586331, 0.0072767 , 0.18913323],
       [0.26225107, 0.70969029, 0.78520986, 0.26621486],
       [0.80821863, 0.78925484, 0.4753357 , 0.8552135 ]])

Згенеруйте 10 випадкових чисел з інтервалу $[a, b)$.

In [29]:
a = 3
b = 5

In [30]:
# Місце для Вашого коду

(np.random.sample(size=10)) * (b - a) + a

array([4.46021389, 3.74750595, 3.76299569, 4.57954444, 3.87287091,
       3.12282222, 3.68905721, 3.53062164, 4.21086827, 3.21726322])

### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [12]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[9 5 3 7 8 1 0 2 6 4]


Перетасуйте матрицю $M$.

In [41]:
M = np.arange(20).reshape((4, 5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [44]:
# Місце для Вашого коду
M = M.reshape(1, 20)[0]
np.random.shuffle(M)
print(M.reshape(4, 5))


[[ 8  9 13 16 19]
 [ 2  7 15  0 18]
 [ 5  1  3 17 11]
 [ 6 12 14 10  4]]


## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [15]:
np.random.seed(42)

In [16]:
print(np.random.randint(10))

6


In [17]:
print(np.random.randint(10))

3


In [18]:
np.random.seed(42)
print(np.random.randint(10))
print(np.random.randint(10))

6
3


In [19]:
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']
[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [22]:
p=0.5
n=10
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)

['H' 'H' 'T' 'H' 'T' 'T' 'H' 'T' 'H' 'H']


In [23]:
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

6 heads and 4 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [54]:
# Місце для Вашого коду

tosses = np.random.choice(['H', 'T'], p=[0.5, 0.5], size=100)
heads = list(tosses).count('H')
tails = list(tosses).count('T')
print("{} heads, and {} tails".format(heads, tails))

50 heads, and 50 tails


### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [77]:
# Місце для Вашого коду

tosses = np.random.randint(2, size=100)
heads = list(tosses).count(1)
tails = list(tosses).count(0)
print("{} heads, and {} tails".format(heads, tails))

51 heads, and 49 tails


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [101]:
# Місце для Вашого коду
tosses = list(map(int, map(round, np.random.sample(size=100))))
heads = tosses.count(1)
tails = tosses.count(0)
print(tosses)
print("{} heads, and {} tails".format(heads, tails))


[0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0]
51 heads, and 49 tails


### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [111]:
# Місце для Вашого коду
for n in [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]:
    tmp_tosses = list(np.random.randint(0, 2, size=n))
    tmp = tmp_tosses.count(1)
    print("n = {}, amount of heads = {}, probability = {}".format(n, tmp, tmp / n))


n = 10, amount of heads = 6, probability = 0.6
n = 50, amount of heads = 25, probability = 0.5
n = 100, amount of heads = 53, probability = 0.53
n = 250, amount of heads = 117, probability = 0.468
n = 500, amount of heads = 259, probability = 0.518
n = 1000, amount of heads = 481, probability = 0.481
n = 2500, amount of heads = 1254, probability = 0.5016
n = 5000, amount of heads = 2540, probability = 0.508
n = 10000, amount of heads = 5043, probability = 0.5043


## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [115]:
# Місце для Вашого коду
test = list(np.random.randint(1, 7, size=60))
print(test)
for i in range(1, 7):
    print("n = {}, amount = {}".format(i, test.count(i)))

[3, 5, 5, 2, 2, 2, 1, 1, 3, 5, 2, 2, 1, 4, 1, 5, 2, 3, 1, 4, 6, 2, 6, 4, 1, 1, 6, 3, 3, 1, 6, 4, 3, 1, 3, 4, 4, 6, 1, 6, 1, 3, 5, 1, 5, 5, 5, 6, 5, 5, 2, 1, 1, 6, 3, 1, 4, 4, 6, 2]
n = 1, amount = 15
n = 2, amount = 9
n = 3, amount = 9
n = 4, amount = 8
n = 5, amount = 10
n = 6, amount = 9


### 4.2 Задача
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [118]:
# Місце для Вашого коду
for n in [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]:
    test = list(np.random.randint(1, 7, size=n))
    probabilities = [test.count(_)/n for _ in range(1, 7)]
    print("n = {}, probabilities = {}".format(n, probabilities))
print(1/6)


n = 10, probabilities = [0.4, 0.1, 0.0, 0.2, 0.2, 0.1]
n = 50, probabilities = [0.18, 0.08, 0.3, 0.08, 0.22, 0.14]
n = 100, probabilities = [0.16, 0.17, 0.19, 0.14, 0.18, 0.16]
n = 250, probabilities = [0.176, 0.128, 0.168, 0.184, 0.176, 0.168]
n = 500, probabilities = [0.206, 0.144, 0.178, 0.158, 0.164, 0.15]
n = 1000, probabilities = [0.161, 0.15, 0.173, 0.17, 0.174, 0.172]
n = 2500, probabilities = [0.1636, 0.1604, 0.1624, 0.1608, 0.1724, 0.1804]
n = 5000, probabilities = [0.16, 0.17, 0.1624, 0.1694, 0.1636, 0.1746]
n = 10000, probabilities = [0.1654, 0.1669, 0.167, 0.1707, 0.1669, 0.1631]
0.16666666666666666


## 5 Колода карт
### 5.1 Реалізація

In [119]:
# Визначимо номінали, масті та карти
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
print(Cards)

[('J', '♣'), ('J', '♡'), ('J', '♠'), ('J', '♢'), ('9', '♣'), ('9', '♡'), ('9', '♠'), ('9', '♢'), ('10', '♣'), ('10', '♡'), ('10', '♠'), ('10', '♢'), ('4', '♣'), ('4', '♡'), ('4', '♠'), ('4', '♢'), ('K', '♣'), ('K', '♡'), ('K', '♠'), ('K', '♢'), ('2', '♣'), ('2', '♡'), ('2', '♠'), ('2', '♢'), ('1', '♣'), ('1', '♡'), ('1', '♠'), ('1', '♢'), ('3', '♣'), ('3', '♡'), ('3', '♠'), ('3', '♢'), ('7', '♣'), ('7', '♡'), ('7', '♠'), ('7', '♢'), ('5', '♣'), ('5', '♡'), ('5', '♠'), ('5', '♢'), ('8', '♣'), ('8', '♡'), ('8', '♠'), ('8', '♢'), ('6', '♣'), ('6', '♡'), ('6', '♠'), ('6', '♢'), ('Q', '♣'), ('Q', '♡'), ('Q', '♠'), ('Q', '♢')]


In [31]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

3♣, 3♠, 3♡, 3♢, 7♣, 7♠, 7♡, 7♢, 9♣, 9♠, 9♡, 9♢, 5♣, 5♠, 5♡, 5♢, 6♣, 6♠, 6♡, 6♢, J♣, J♠, J♡, J♢, 4♣, 4♠, 4♡, 4♢, Q♣, Q♠, Q♡, Q♢, 8♣, 8♠, 8♡, 8♢, 10♣, 10♠, 10♡, 10♢, 1♣, 1♠, 1♡, 1♢, 2♣, 2♠, 2♡, 2♢, K♣, K♠, K♡, K♢


In [32]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♣3, ♣7, ♣9, ♣5, ♣6, ♣J, ♣4, ♣Q, ♣8, ♣10, ♣1, ♣2, ♣K
♠3, ♠7, ♠9, ♠5, ♠6, ♠J, ♠4, ♠Q, ♠8, ♠10, ♠1, ♠2, ♠K
♡3, ♡7, ♡9, ♡5, ♡6, ♡J, ♡4, ♡Q, ♡8, ♡10, ♡1, ♡2, ♡K
♢3, ♢7, ♢9, ♢5, ♢6, ♢J, ♢4, ♢Q, ♢8, ♢10, ♢1, ♢2, ♢K


In [33]:
# Перемішаємо колоду
np.random.shuffle(Cards)

print(Cards)

[('Q', '♠'), ('10', '♡'), ('3', '♡'), ('2', '♠'), ('2', '♣'), ('10', '♢'), ('J', '♡'), ('1', '♢'), ('9', '♡'), ('3', '♣'), ('6', '♡'), ('Q', '♡'), ('K', '♣'), ('8', '♠'), ('J', '♠'), ('7', '♣'), ('K', '♡'), ('8', '♣'), ('5', '♣'), ('Q', '♢'), ('J', '♣'), ('J', '♢'), ('4', '♡'), ('1', '♡'), ('5', '♡'), ('5', '♢'), ('1', '♣'), ('1', '♠'), ('9', '♠'), ('10', '♣'), ('9', '♢'), ('2', '♢'), ('6', '♠'), ('Q', '♣'), ('10', '♠'), ('7', '♠'), ('2', '♡'), ('K', '♢'), ('8', '♢'), ('6', '♣'), ('K', '♠'), ('8', '♡'), ('7', '♢'), ('7', '♡'), ('4', '♢'), ('6', '♢'), ('3', '♠'), ('4', '♠'), ('9', '♣'), ('5', '♠'), ('4', '♣'), ('3', '♢')]


### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [126]:
# Місце для Вашого коду
norm_cards = list(map(lambda a: str(a[0]) + ' ' + str(a[1]), Cards))
print(norm_cards)
for n in [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]:
    test = np.random.choice(norm_cards, size=n, replace=True)
    amount = len([el for el in test if el[0] in ['2', '4', '6', '8', '10']])
    print("n = {}, amount of even cards = {}, probability = {}".format(n, amount, amount/n))


['J ♣', 'J ♡', 'J ♠', 'J ♢', '9 ♣', '9 ♡', '9 ♠', '9 ♢', '10 ♣', '10 ♡', '10 ♠', '10 ♢', '4 ♣', '4 ♡', '4 ♠', '4 ♢', 'K ♣', 'K ♡', 'K ♠', 'K ♢', '2 ♣', '2 ♡', '2 ♠', '2 ♢', '1 ♣', '1 ♡', '1 ♠', '1 ♢', '3 ♣', '3 ♡', '3 ♠', '3 ♢', '7 ♣', '7 ♡', '7 ♠', '7 ♢', '5 ♣', '5 ♡', '5 ♠', '5 ♢', '8 ♣', '8 ♡', '8 ♠', '8 ♢', '6 ♣', '6 ♡', '6 ♠', '6 ♢', 'Q ♣', 'Q ♡', 'Q ♠', 'Q ♢']
n = 10, amount of even cards = 3, probability = 0.3
n = 50, amount of even cards = 11, probability = 0.22
n = 100, amount of even cards = 31, probability = 0.31
n = 250, amount of even cards = 81, probability = 0.324
n = 500, amount of even cards = 150, probability = 0.3
n = 1000, amount of even cards = 299, probability = 0.299
n = 2500, amount of even cards = 745, probability = 0.298
n = 5000, amount of even cards = 1528, probability = 0.3056
n = 10000, amount of even cards = 3157, probability = 0.3157


### 5.3 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [35]:
# Місце для Вашого коду



### 5.4 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав від 2 до 5 карт кожної масті. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♣7, ♢K, ♡9, ♡1, ♡5}.

In [36]:
# Місце для Вашого коду

